services:
  app:
    build: .
    working_dir: /app
    depends_on:
      - firebase
    command: npm run dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - FIRESTORE_EMULATOR_HOST="0.0.0.0:8080"
  firebase:
    build:
      context: .
      dockerfile: Dockerfile.firebase
    command: firebase emulators:start --import ./firebase/dev-data
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '3001:3001'
      - '9099:9099'
      - '5001:5001'
      - '8080:8080'
    environment:
      - NODE_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=./service-account.json
